apiVersion: v1
kind: Pod
metadata:
  name: high-cpu-pod
  namespace: stress-test
  labels:
    app: stress-test
    type: high-cpu
spec:
  containers:
  - name: stress-cpu
    image: containerstack/cpustress:latest
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    command: ["/bin/sh", "-c"]
    args: ["while true; do dd if=/dev/zero of=/dev/null bs=1M count=100; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: high-memory-pod
  namespace: stress-test
  labels:
    app: stress-test
    type: high-memory
spec:
  containers:
  - name: stress-memory
    image: polinux/stress:latest
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "400M", "--vm-hang", "0"]
---
apiVersion: v1
kind: Pod
metadata:
  name: crash-loop-pod
  namespace: stress-test
  labels:
    app: stress-test
    type: crash-loop
spec:
  containers:
  - name: crash-container
    image: busybox:latest
    command: ["/bin/sh", "-c"]
    args: ["sleep 10 && exit 1"]
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-stress
  namespace: stress-test
  labels:
    app: network-stress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: network-stress
  template:
    metadata:
      labels:
        app: network-stress
    spec:
      containers:
      - name: network-test
        image: nginx:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: normal-workload
  namespace: stress-test
  labels:
    app: normal-workload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: normal-workload
  template:
    metadata:
      labels:
        app: normal-workload
    spec:
      containers:
      - name: app
        image: nginx:latest
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 80

